mvee/mvee/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views as user_views
from django.contrib.auth import views as auth_views


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),

    path('register/', user_views.register, name='register'),
    path('sellplan/', user_views.sellplan, name='sellplan'),
    path('hire/', user_views.Hire, name='hire'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('phone_number/', user_views.mpesaNumber, name='phone_number'),
	path('make_payment/', user_views.makePayment, name='make_payment'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mvee/store/urls.py
from django.urls import path

from .import views

urlpatterns = [
	path('',views.home, name='home'),
	path('store/',views.store, name='store'),
	path('cart/',views.cart, name='cart'),
	path('detail/<int:pk>/',views.DetailView, name='detail'),
	path('update_item/', views.updateItem, name='update_item'),
	path('checkout/', views.checkout, name='checkout'),
	path('process_order/', views.processOrder, name='process_order'),
	path('about/', views.about, name='about'),
	path('products/', views.store2, name='other_products'),

	#mpesa api urls
	path('access/token/', views.getAccessToken, name='get_mpesa_access_token'),
	path('online/lipa', views.lipa_na_mpesa_online, name='lipa_na_mpesa'),
]

mvee/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now

# Create your models here.
class Customer(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE, null=True, blank=True)
	name = models.CharField(max_length=100)
	email = models.EmailField()

	def __str__(self):
		return self.name

@receiver(post_save, sender=User)
def assign_user_customer(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_customer(sender, instance, **kwargs):
    instance.customer.save()

class Product(models.Model):
	name = models.CharField(max_length=100)
	price = models.DecimalField(decimal_places=2, max_digits=9)
	description = models.TextField(null=True, blank=True)
	featured = models.ImageField(null=True, blank=True)
	
	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.featured.url
		except Exception as e:
			url = ''
		return url


class Image(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	name = models.CharField(max_length=200)
	image = models.ImageField()

	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		print('URL:', url)
		return url


class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	date_ordered = models.DateTimeField(default=now)
	complete = models.BooleanField(default=False)
	transaction_id = models.CharField(max_length=200)

	def __str__(self):
		return str(self.id)


	@property
	def cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total

	@property
	def cart_totals(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total
	
	

class OrderItem(models.Model):
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
	quantity = models.IntegerField(default=0)
	date_added = models.DateTimeField(default=now)

	@property
	def get_total(self):
		total = self.product.price * self.quantity
		return total

#The model for the other products other than house plans
class OtherProducts(models.Model):
	name = models.CharField(max_length=100)
	price = models.DecimalField(decimal_places=2, max_digits=9)
	description = models.TextField(null=True, blank=True)
	featured = models.ImageField(null=True, blank=True)
	
	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.featured.url
		except Exception as e:
			url = ''
		return url

mvee/store/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
import datetime
import json
import requests
from requests.auth import HTTPBasicAuth


from .models import *
from .utils import cartData

from users.forms import phoneNumber
from users.views import mpesaNumber, makePayment
from users.models import PhoneNumber

#lipa na mpesa imports
from . mpesa_credentials import MpesaAccessToken, LipanaMpesaPpassword

# Create your views here.
def store(request):
    products = Product.objects.all()
    
    data = cartData(request)
    cartItems = data['cartItems']

    context = {'products':products, 'cartItems':cartItems}
    return render(request, 'store/store.html', context)

def cart(request):
    data = cartData(request)
    items = data['items']
    order = data['order']
    cartItems = data['cartItems']

    context = {'items':items, 'order':order, 'cartItems':cartItems}
    return render(request, 'store/cart.html', context)

def checkout(request):
    data = cartData(request)
    items = data['items']
    order = data['order']
    cartItems = data['cartItems'] 

    context = {'items':items, 'cartItems':cartItems, 'order':order}
    return render(request, 'store/checkout.html', context)

def DetailView(request, pk):
    detail = Product.objects.get(id=pk)

    data = cartData(request)
    cartItems = data['cartItems']

    context = {'detail':detail, 'cartItems':cartItems}
    return render(request, 'store/detail.html', context)

def updateItem(request):
    data = json.loads(request.body)
    action = data['action']
    productId = data['productId']

    print('productId:',productId)
    print('Action:', action)

    customer = request.user.customer
    product = Product.objects.get(id=productId)

    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    data = json.loads(request.body)
    transaction_id = datetime.datetime.now().timestamp()

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['CustomerData']['totals'])
        order.transaction_id = transaction_id

        if total == order.cart_totals:
            order.complete = True
        order.save()
        
    else:
        print('user is not logged in...')
    return JsonResponse('Payment complete...', safe=False)


def about(request):
    return render(request, 'store/about.html')

def home(request):
    return render(request, 'store/home.html')

#The view for the other products other than house plans
def store2(request):
  products = OtherProducts.objects.all()
    
  data = cartData(request)
  cartItems = data['cartItems']

  context = {'products':products, 'cartItems':cartItems}
  return render(request, 'store/otherproducts.html', context)


#views for MPESA api
def getAccessToken(request):
    consumer_key = 'FyJ7vtoCncsgGv2kKLafWIjk0xQQLEWC'
    consumer_secret = 'D18c2odsaih8MOWR'
    api_URL = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'

    r = requests.get(api_URL, auth=HTTPBasicAuth(consumer_key, consumer_secret))
    # print(r.content)
    mpesa_access_token = r.json()
    validated_mpesa_access_token = mpesa_access_token['access_token']

    return HttpResponse(validated_mpesa_access_token)


def lipa_na_mpesa_online(request):
    phone_number = str(PhoneNumber.objects.all()[0])
    print(phone_number)
    data = cartData(request)
    order = data['order']
  
    access_token = MpesaAccessToken.validated_mpesa_access_token
    api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
    headers = {"Authorization": "Bearer %s" % access_token}
    request = {
        "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,
        "Password": LipanaMpesaPpassword.decode_password,
        "Timestamp": LipanaMpesaPpassword.lipa_time,
        "TransactionType": "CustomerPayBillOnline",
        "Amount": float(order.cart_totals),
        "PartyA": phone_number,  # replace with your phone number to get stk push
        "PartyB": LipanaMpesaPpassword.Business_short_code,
        "PhoneNumber": phone_number,  # replace with your phone number to get stk push
        "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",
        "AccountReference": "Victor",
        "TransactionDesc": "Testing stk push"
    }
    response = requests.post(api_url, json=request, headers=headers)
    return HttpResponse('success')

mvee/store/templates/store/about.html
{% extends 'store/base.html' %}

{% block content %}
    <div class=" container box-element mt-4">
        <p>
            We are a company that offer our services online. Our base is in Nairobi, Kenya. We offer real estate services
            like selling home plans, getting your desired plan designed in a short time after submitting all you want done
            and many other services. We also sell other goodies at a very cheap price. Be sure to check out our services
            you will for sure like it.
        </p>
    </div>
{% endblock %}

mvee/store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<script type="text/javascript">
		var user = '{{request.user}}'

		function getToken(name) {
	    let cookieValue = null;
	    if (document.cookie && document.cookie !== '') {
	        const cookies = document.cookie.split(';');
	        for (let i = 0; i < cookies.length; i++) {
	            const cookie = cookies[i].trim();
	            // Does this cookie string begin with the name we want?
	            if (cookie.substring(0, name.length + 1) === (name + '=')) {
	                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
	                break;
	            }
	        }
	    }
	    return cookieValue;
		}
		var csrftoken = getToken('csrftoken');
	</script>

	<title>MVEE</title>
</head>
<body>
	
	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
	  
	    <a class="navbar-brand" href="{% url 'home' %}">
	          <h3 style="margin-left: 20px;">HomesCompany</h3>
	        </a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
	          <span class="navbar-toggler-icon"></span>
	        </button>
	    <div class="collapse navbar-collapse" id="navbarResponsive">
	      <ul class="navbar-nav ml-auto">
	      	<!-- <li class="nav-item">
	          <a href="#">
	    		<img  id="cart-icon" src="{% static 'images/cart.png' %}">
	    		<p id="cart-total">4</p>
	    	
	        </li> -->
	        <div class="form-inline my-2 my-lg-0">
		     	<div class="dropdown">
				  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    My Account
				  </button>
				  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				  	{% if user.is_authenticated %}
				  		<a class="dropdown-item" href="{% url 'hire' %}">Hire an Architect</a>
				  		<a class="dropdown-item" href="{% url 'sellplan' %}">Sell HousePlan</a>
				  		<a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
				  	{% else %}
					    <a class="dropdown-item" href="{% url 'login' %}">Log in</a>
					    <a class="dropdown-item" href="{% url 'register' %}">Sign up</a>
					{% endif %}
				  </div>
				</div>
		     	
		     	<a href="{% url 'cart' %}">
		    		<img  id="cart-icon" src="{% static 'images/cart.png' %}">
		    	</a>
		    	<p id="cart-total">{{cartItems}}</p>

		    </div>
	        
	       
	       	</ul>
	    </div>
	  
	</nav>

	<div class="container">
		{%if messages%}
			{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">
					{{ message }}
				</div>
			{% endfor %}
		{% endif %}
		{% block content %}{% endblock %}
		<br>

	</div>

	<footer class="section footer-classic context-dark bg-image" style="background: #2d3246;">
	    <div class="container">
	      <div class="row row-30">
	        <div class="col-md-4 col-xl-5">
	          <div class="pr-xl-4"><a class="brand" href="index.html"><img class="brand-logo-light" src="images/agency/logo-inverse-140x37.png" alt="" width="140" height="37" srcset="images/agency/logo-retina-inverse-280x74.png 2x"></a>
	            <p class="rights"><span>©  </span><span class="copyright-year">2020</span><span> </span><span>Company</span><span> - </span><span>All Rights Reserved.</span></p>
	          </div>
	        </div>
	        <div class="col-md-4">
	          <h5>Contacts</h5>
	          <dl class="contact-list">
	            <dt>Address:</dt>
	            <dd>798 South Park Avenue, New York, USA</dd>
	          </dl>
	          <dl class="contact-list">
	            <dt>email:</dt>
	            <dd><a href="mailto:#">victormuia8@gmail.com</a></dd>
	          </dl>
	          <dl class="contact-list">
	            <dt>phones:</dt>
	            <dd><a href="tel:#">+254710295224</a> <span>or</span> <a href="tel:#">+254702510352</a>
	            </dd>
	          </dl>
	        </div>
	        <div class="col-md-4 col-xl-3">
	          <h5>Links</h5>
	          <ul class="nav-list">
	            <li><a href="{% url 'about' %}">About</a></li>
	          </ul>
	        </div>
	      </div>
	    </div>
	    <!-- <div class="row no-gutters social-container">
	      <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-facebook"></span><span>Facebook</span></a></div>
	      <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-instagram"></span><span>Instagram</span></a></div>
	      <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-twitter"></span><span>Twitter</span></a></div>
	      <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-youtube-play"></span><span>Youtube</span></a></div>
	    </div>
	  </footer> -->

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script type="text/javascript" src="{% static 'js/cart.js' %}">	</script>
</body>
</html>

mvee/store/templates/store/cart.html
{% extends 'store/base.html' %}
{% load static %}


{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190; Continue Shopping</a>
				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> Ksh {{order.cart_totals}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>
			</div>

			<div class="box-element">
				<div class="cart-row">
				<div style="flex:2"></div>
				<div style="flex:2"><strong>Item</strong></div>
				<div style="flex:1"><strong>Price</strong></div>
				<div style="flex:1"><strong>Quantity</strong></div>
				<div style="flex:1"><strong>Total</strong></div>
			</div>

			{% for item in items %}
			<div class="cart-row">
				<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
				<div style="flex:2"><p>{{item.product.name}}</p></div>
				<div style="flex:1"><p>Ksh {{item.product.price}}</p></div>
				<div style="flex:1">
					<p class="quantity">{{item.quantity}}</p>
					<div class="quantity">
						<img data-product='{{item.product.id}}' data-action = 'add' class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
				
						<img data-product='{{item.product.id}}' data-action = 'remove' class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
					</div>
				</div>
				<div style="flex:1"><p>Ksh {{item.get_total}}</p></div>
			</div>
			{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

mvee/store/templates/store/checkout.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
	<div class="row">
		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
					<div class="cart-row">
						<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
						<div style="flex:2"><p>{{item.product.name}}</p></div>
						<div style="flex:1"><p>Ksh {{item.product.price}}</p></div>
						<div style="flex:1"><p>x{{item.quantity}}</p></div>
					</div>
				{% endfor %}
					<h5>Items:   {{order.cart_items}}</h5>
					<h5>Total:   Ksh {{order.cart_totals}}</h5>
				
			</div>
		</div>

		<div class="col-lg-6 mt-4">
			<h4><strong>Name:</strong>   {{request.user}}</h4><br>
			<hr>
			<h4><strong>Email:</strong>  {{request.user.email}}</h4><br>
			<hr>

			<div class="box-element" id="payment-info">
				<small>Paypal Options</small>
				<!-- <button id="make-payment">Make Payment</button> -->
				<div id="paypal-button-container"></div>
			</div>

			<div class="box-element mt-4">
				<small>Lipa na MPESA Options</small>
				<br>
				<a href="{% url 'phone_number' %}"><img class="lipanampesatag" src="{% static 'images/lipanampesa.png' %}" alt=""></a>
			</div>
		</div>
		
	</div>

	 <script src="https://www.paypal.com/sdk/js?client-id=AQjz1-yF32rEns84DpFwhwJq-D4-1cJkbbQc__rJCh-LtQQPL9jTOWhdRL6ilVmZ-lC3dERda8NB32S9&currency=USD">
	 	
	 </script>

	 <script>
	 	var totals = '{{order.cart_totals}}'
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

        	style:{
        		color: 'blue',
        		shape: 'rect'
        	},

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(totals).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    saveCustomerDetails()
                });
            }


        }).render('#paypal-button-container');
    </script>

	<script type="text/javascript">


		// document.getElementById('make-payment').addEventListener('click', function(e){
		// 	saveCustomerDetails()
		// })

		function saveCustomerDetails(){
			console.log('Payment button clicked...')

			var customerData = {
				'name': '{{request.user}}',
				'email': '{{request.user.email}}',
				'totals': totals,
			}

			var url = '/process_order/'

			fetch(url,{
			method:'POST',
			headers:{
				'Content-Type':'application/json',
				'X-CSRFToken': csrftoken,
			},
			body:JSON.stringify({'CustomerData':customerData})
			})

			.then((response)=>response.json())
			.then((data)=>{
				console.log('Success:', data)
				alert('Transaction completed')
				window.location.href = "{% url 'store' %}"

				// cart = {}
				// document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
				 })
		}
	</script>
	
{% endblock %}

mvee/store/templates/store/detail.html
{% extends 'store/base.html' %}
<!-- {% load static %} -->


{% block content %}
	<!-- <div class="detail mt-4">
		<div class="detail-element">
			<img class="thumbnail" src="{{detail.imageURL}}"><br>
		</div>
		<div class="detail-element">
			<h6><strong>{{detail.name}}</strong></h6>
			<hr>
			{{detail.description}}<br>
			<hr>

			<button style="display: inline-block; float: right" data-product={{detail.id}} data-action="add" class="btn btn-success add-btn update-cart">Add to Cart</button>
			<h4><strong>${{detail.price}}</strong></h4>

		</div>
	</div> -->


	<div id="content-wrapper">
		<div class="column">
			<img id="featured" src="{{detail.imageURL}}">

			<div id="slide-wrapper">
				<img id="slideLeft" class="arrow" src="{% static 'images/arrow-left.png' %}">

				<div id="slider">
					{% for image in detail.image_set.all%}

				
						<img class="thumbnail-detail" src="{{image.imageURL}}">

					{% endfor %}
			
				</div>

				<img id="slideRight" class="arrow" src="{% static 'images/arrow-right.png' %}">
			</div>
		</div>

		<div class="column">
			<h1>{{detail.name}}</h1>
			<hr>
			<h3>${{detail.price}}</h3>
			<hr>

			<p>{{detail.description}}</p>
			<hr>

			<!-- <input value=1 type="number"> -->
			<div style="display: inline-block;">
				<button data-product={{detail.id}} data-action = 'add' class="btn btn-dark update-cart">Add to Cart</button>
				<a href="{% url 'store' %}" class="btn btn-dark">Go Back</a>
			</div>
			

		</div>
	</div>

{% endblock %}

mvee/store/templates/store/home.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
    <div class="box-element mt-4">
        <h2>Welcome to MVEE. We value our clients 
            and serve them with diligence.
        </h2>
    </div>

    <h3 style="text-align: center; margin-top: 10px;"><u>Services we offer</u></h3>

    <div class="homebox">
        <div class="partition box-element">
            <div class="box-element">
                <p>Want to build a house and do not have a plan? Here are some awesome ready house plans you can check.</p>
                <a href="{% url 'store' %}"><img class="homeplanbuttons" src="{% static 'images/readyhouseplan.jpeg' %}" alt=""> Get a ready house plan</a>
            </div>

            <div class="box-element">
                <p>Are you an architect and have designed a plan that you wish to market? Submit it here and we will help you sell it.</p>
                <a href="{% url 'sellplan' %}"><img class="homeplanbuttons" src="{% static 'images/sellhouse.jpeg' %}" alt=""> Sell house plan</a>
            </div>

            <div class="box-element">
                <p>Do you have specifications on how your house should look like? Hire an architect from our our team and get your desired design fast</p>
                <a href="{% url 'hire' %}"><img class="homeplanbuttons" src="{% static 'images/hirearchitect.jpeg' %}" alt=""> Hire an Architect</a>
            </div>
        </div>
        <div class="partition box-element">
            <!-- <p>
                We offer other products too. We sell laptops, office accessories and many other produts that you might like.
                Be sure to check what we have in our store that might interest you using the link below.
            </p>
            <a href="{% url 'other_products' %}"><img class="homeplanbuttons" src="{% static 'images/products.jpeg' %}" alt=""> Check other products</a> -->

        </div>
    </div>
{% endblock %}

mvee/store/templates/store/otherproducts.html
{% extends 'store/base.html' %}


{% block content %}
<div class="row">
	{% for product in products %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{product.imageURL}}"><br>
			<div class="box-element product">
				<h6><strong>{{product.name}}</strong></h6>
				<hr>

				<button data-product={{product.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>Ksh {{product.price}}</strong></h4>

			</div>
		</div>
	{% endfor %}
</div>
{% endblock %}

mvee/store/templates/store/store.html
{% extends 'store/base.html' %}


{% block content %}
<div class="row">
	{% for product in products %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{product.imageURL}}"><br>
			<div class="box-element product">
				<h6><strong>{{product.name}}</strong></h6>
				<hr>

				<button data-product={{product.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
				<a class="btn btn-outline-success" href="{% url 'detail' product.id %}">View</a>
				<h4 style="display: inline-block; float: right"><strong>KSh {{product.price}}</strong></h4>

			</div>
		</div>
	{% endfor %}
</div>
{% endblock %}